# This is a basic workflow to help you get started with Actions

name: Build and test

on:
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build
      - name: Test
        run: npm test
